(() => {
  const mobileFix=document.createElement("style");
  mobileFix.textContent='body{overflow-x:hidden}@media(max-width:600px){.admin-topbar{gap:12px;padding-right:82px}.admin-topbar>div:nth-child(2){min-width:0}.admin-topbar h1{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.top-actions{position:absolute;right:15px;top:12px}.top-actions .primary-button{width:56px;padding:10px 7px;font-size:0}.top-actions .primary-button:after{content:"Save";font-size:12px}}';
  document.head.appendChild(mobileFix);
  const KEY="supermatrix_admin_settings_v1";
  const defaults={homepage:{heroTitle:"Mutual fund investing with guidance at every step.",heroDescription:"Plan around real financial goals, explore mutual fund solutions, and get access to professional support throughout your investment journey.",primaryCta:"Talk to the team",secondaryCta:"Try the SIP Calculator"},contact:{supportEmail:"support@supermatrix.in",supportPhone:"022-26528671 / 72",supportPhoneLink:"02226528671",mumbaiAddress:"401, 4th Floor, Manek Plaza, 167, Vidya Nagari Marg, Kalina, Santacruz (East), Mumbai – 400098",delhiAddress:"411, Pratap Bhawan, 5, Bahadurshah Zafar Marg, New Delhi – 110002"},chatbot:{chatbotEnabled:true,chatbotLabel:true,chatbotGreeting:"Hi! I’m the SuperMatrix FAQ assistant. What would you like to understand?"},calculators:{sipAmount:10000,sipYears:15,sipRate:12},compliance:{legalEntity:"",cin:"",arn:"",arnValidity:"",euin:"",grievanceName:"",grievanceEmail:"",grievancePhone:"",disclosure:"Mutual Fund investments are subject to market risks. Please read all scheme-related documents carefully before investing. Past performance does not guarantee future returns."}};
  let settings=load();
  const titles={overview:"Overview",homepage:"Homepage",contact:"Contact & Offices",chatbot:"FAQ Chatbot",calculators:"Calculators",compliance:"Compliance",data:"Import / Export"};
  function clone(v){return JSON.parse(JSON.stringify(v))}
  function merge(base,value){const result=clone(base);Object.keys(result).forEach(group=>Object.assign(result[group],value?.[group]||{}));return result}
  function load(){try{return merge(defaults,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return clone(defaults)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(settings));document.getElementById("saveStatus").textContent="All changes saved locally"}
  function showPanel(id){document.querySelectorAll(".admin-panel").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll(".admin-sidebar nav button").forEach(b=>b.classList.toggle("active",b.dataset.panel===id));document.getElementById("panelTitle").textContent=titles[id];document.querySelector(".admin-sidebar").classList.remove("open");scrollTo(0,0)}
  function populate(){document.querySelectorAll(".settings-form").forEach(form=>{const group=form.dataset.group;Object.entries(settings[group]).forEach(([name,value])=>{const input=form.elements[name];if(!input)return;if(input.type==="checkbox")input.checked=Boolean(value);else input.value=value})})}
  function capture(form){const group=form.dataset.group;[...form.elements].forEach(input=>{if(!input.name)return;settings[group][input.name]=input.type==="checkbox"?input.checked:input.type==="number"?Number(input.value):input.value});document.getElementById("saveStatus").textContent="Saving…";save()}
  function toast(text){const el=document.querySelector(".toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
  document.querySelectorAll(".admin-sidebar nav button").forEach(b=>b.addEventListener("click",()=>showPanel(b.dataset.panel)));document.querySelectorAll("[data-jump]").forEach(b=>b.addEventListener("click",()=>showPanel(b.dataset.jump)));document.querySelector(".menu-button").addEventListener("click",()=>document.querySelector(".admin-sidebar").classList.toggle("open"));document.querySelectorAll(".settings-form").forEach(form=>form.addEventListener("input",()=>capture(form)));
  document.getElementById("applyButton").addEventListener("click",()=>{save();toast("Local settings applied");});
  document.getElementById("exportButton").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(settings,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="supermatrix-settings.json";a.click();URL.revokeObjectURL(a.href);toast("Configuration exported")});
  document.getElementById("importInput").addEventListener("change",async event=>{const file=event.target.files[0];if(!file)return;try{settings=merge(defaults,JSON.parse(await file.text()));save();populate();toast("Configuration imported")}catch{toast("Invalid configuration file")}event.target.value=""});
  document.getElementById("resetButton").addEventListener("click",()=>{if(!confirm("Reset all locally saved settings?"))return;settings=clone(defaults);localStorage.removeItem(KEY);populate();toast("Local settings reset")});
  populate();
})();
